spring:
  application:
    name: movie-service
  redis:
    host: localhost
    port: '6379'
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: '8000'
eureka:
  instance:
    instance-id: movie-service:${random.uuid}
